[2023-10-03T09:53:14.148+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.282+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.307+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:14.472+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-16 00:00:00+00:00
[2023-10-03T09:53:14.522+0000] {standard_task_runner.py:57} INFO - Started process 3090 to run task
[2023-10-03T09:53:14.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-16T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpx5khe4yq']
[2023-10-03T09:53:14.564+0000] {standard_task_runner.py:85} INFO - Job 174: Subtask preprocess_data
[2023-10-03T09:53:14.939+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:16.156+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-16T00:00:00+00:00'
[2023-10-03T09:53:16.180+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:16.269+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230916T000000, start_date=20231003T095314, end_date=20231003T095316
[2023-10-03T09:53:16.453+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 174 for task preprocess_data (name 'task_instance' is not defined; 3090)
[2023-10-03T09:53:16.630+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:16.777+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:41.904+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T10:02:41.960+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T10:02:41.963+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:42.078+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-16 00:00:00+00:00
[2023-10-03T10:02:42.143+0000] {standard_task_runner.py:57} INFO - Started process 3381 to run task
[2023-10-03T10:02:42.216+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-16T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpwj419vze']
[2023-10-03T10:02:42.216+0000] {standard_task_runner.py:85} INFO - Job 243: Subtask preprocess_data
[2023-10-03T10:02:42.672+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:43.597+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-16T00:00:00+00:00'
[2023-10-03T10:02:43.598+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:43.667+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230916T000000, start_date=20231003T100241, end_date=20231003T100243
[2023-10-03T10:02:43.847+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 243 for task preprocess_data (name 'task_instance' is not defined; 3381)
[2023-10-03T10:02:43.892+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:43.992+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:17.814+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T10:06:18.163+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T10:06:18.178+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:18.419+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-16 00:00:00+00:00
[2023-10-03T10:06:18.492+0000] {standard_task_runner.py:57} INFO - Started process 3623 to run task
[2023-10-03T10:06:18.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-16T00:00:00+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpi8iesq5h']
[2023-10-03T10:06:18.517+0000] {standard_task_runner.py:85} INFO - Job 332: Subtask preprocess_data
[2023-10-03T10:06:18.755+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:19.729+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-16T00:00:00+00:00'
[2023-10-03T10:06:19.842+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:19.913+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230916T000000, start_date=20231003T100617, end_date=20231003T100619
[2023-10-03T10:06:20.096+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 332 for task preprocess_data ('NoneType' object has no attribute 'get'; 3623)
[2023-10-03T10:06:20.228+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:20.484+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:54.833+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T10:16:55.024+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [queued]>
[2023-10-03T10:16:55.042+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:55.283+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-16 00:00:00+00:00
[2023-10-03T10:16:55.337+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-16T00:00:00+00:00', '--job-id', '424', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpx11ybe4a']
[2023-10-03T10:16:55.338+0000] {standard_task_runner.py:85} INFO - Job 424: Subtask preprocess_data
[2023-10-03T10:16:55.312+0000] {standard_task_runner.py:57} INFO - Started process 3990 to run task
[2023-10-03T10:16:55.772+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-16T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:56.699+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-16T00:00:00+00:00'
[2023-10-03T10:16:57.000+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:57.050+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230916T000000, start_date=20231003T101654, end_date=20231003T101657
[2023-10-03T10:16:57.240+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 424 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3990)
[2023-10-03T10:16:57.313+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:57.443+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
