[2023-10-03T09:53:14.234+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.424+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.433+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:14.632+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-19 00:00:00+00:00
[2023-10-03T09:53:14.661+0000] {standard_task_runner.py:57} INFO - Started process 3091 to run task
[2023-10-03T09:53:14.684+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-19T00:00:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpvyluz_v7']
[2023-10-03T09:53:14.693+0000] {standard_task_runner.py:85} INFO - Job 175: Subtask preprocess_data
[2023-10-03T09:53:15.061+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:16.335+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-19T00:00:00+00:00'
[2023-10-03T09:53:16.345+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:16.372+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230919T000000, start_date=20231003T095314, end_date=20231003T095316
[2023-10-03T09:53:16.590+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 175 for task preprocess_data (name 'task_instance' is not defined; 3091)
[2023-10-03T09:53:16.751+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:16.870+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:41.896+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T10:02:42.011+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T10:02:42.018+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:42.126+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-19 00:00:00+00:00
[2023-10-03T10:02:42.159+0000] {standard_task_runner.py:57} INFO - Started process 3382 to run task
[2023-10-03T10:02:42.206+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-19T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp5zl7gcr5']
[2023-10-03T10:02:42.207+0000] {standard_task_runner.py:85} INFO - Job 242: Subtask preprocess_data
[2023-10-03T10:02:42.670+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:43.286+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-19T00:00:00+00:00'
[2023-10-03T10:02:43.286+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:43.299+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230919T000000, start_date=20231003T100241, end_date=20231003T100243
[2023-10-03T10:02:43.338+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 242 for task preprocess_data (name 'task_instance' is not defined; 3382)
[2023-10-03T10:02:43.355+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:43.447+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:19.988+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T10:06:20.092+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T10:06:20.099+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:20.189+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-19 00:00:00+00:00
[2023-10-03T10:06:20.214+0000] {standard_task_runner.py:57} INFO - Started process 3628 to run task
[2023-10-03T10:06:20.240+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-19T00:00:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpvotu8pdy']
[2023-10-03T10:06:20.250+0000] {standard_task_runner.py:85} INFO - Job 335: Subtask preprocess_data
[2023-10-03T10:06:20.824+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:21.717+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-19T00:00:00+00:00'
[2023-10-03T10:06:21.825+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:21.879+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230919T000000, start_date=20231003T100619, end_date=20231003T100621
[2023-10-03T10:06:22.031+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 335 for task preprocess_data ('NoneType' object has no attribute 'get'; 3628)
[2023-10-03T10:06:22.102+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:22.234+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:56.347+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.474+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.490+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:56.704+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-19 00:00:00+00:00
[2023-10-03T10:16:56.779+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-19T00:00:00+00:00', '--job-id', '426', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmprhh1qh3w']
[2023-10-03T10:16:56.791+0000] {standard_task_runner.py:85} INFO - Job 426: Subtask preprocess_data
[2023-10-03T10:16:56.823+0000] {standard_task_runner.py:57} INFO - Started process 3993 to run task
[2023-10-03T10:16:57.221+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-19T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:58.267+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-19T00:00:00+00:00'
[2023-10-03T10:16:58.362+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:58.410+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230919T000000, start_date=20231003T101656, end_date=20231003T101658
[2023-10-03T10:16:58.528+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 426 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3993)
[2023-10-03T10:16:58.644+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:58.859+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
