[2023-10-03T09:53:16.889+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T09:53:17.102+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T09:53:17.122+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:17.356+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-17 00:00:00+00:00
[2023-10-03T09:53:17.408+0000] {standard_task_runner.py:57} INFO - Started process 3100 to run task
[2023-10-03T09:53:17.420+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-17T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmprze68kbu']
[2023-10-03T09:53:17.429+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask preprocess_data
[2023-10-03T09:53:18.216+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:19.203+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-17T00:00:00+00:00'
[2023-10-03T09:53:19.212+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:19.280+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230917T000000, start_date=20231003T095316, end_date=20231003T095319
[2023-10-03T09:53:19.424+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 184 for task preprocess_data (name 'task_instance' is not defined; 3100)
[2023-10-03T09:53:19.468+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:19.536+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:41.894+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T10:02:41.953+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T10:02:41.960+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:42.072+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-17 00:00:00+00:00
[2023-10-03T10:02:42.105+0000] {standard_task_runner.py:57} INFO - Started process 3380 to run task
[2023-10-03T10:02:42.156+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-17T00:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpr1_cs_n9']
[2023-10-03T10:02:42.157+0000] {standard_task_runner.py:85} INFO - Job 241: Subtask preprocess_data
[2023-10-03T10:02:42.693+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:43.556+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-17T00:00:00+00:00'
[2023-10-03T10:02:43.557+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:43.704+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230917T000000, start_date=20231003T100241, end_date=20231003T100243
[2023-10-03T10:02:43.821+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 241 for task preprocess_data (name 'task_instance' is not defined; 3380)
[2023-10-03T10:02:43.913+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:44.017+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:17.796+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T10:06:18.141+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T10:06:18.142+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:18.261+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-17 00:00:00+00:00
[2023-10-03T10:06:18.309+0000] {standard_task_runner.py:57} INFO - Started process 3622 to run task
[2023-10-03T10:06:18.337+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-17T00:00:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpw9xsbzer']
[2023-10-03T10:06:18.350+0000] {standard_task_runner.py:85} INFO - Job 331: Subtask preprocess_data
[2023-10-03T10:06:18.529+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:19.125+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-17T00:00:00+00:00'
[2023-10-03T10:06:19.234+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:19.273+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230917T000000, start_date=20231003T100617, end_date=20231003T100619
[2023-10-03T10:06:19.433+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 331 for task preprocess_data ('NoneType' object has no attribute 'get'; 3622)
[2023-10-03T10:06:19.524+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:19.658+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:54.880+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T10:16:55.103+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [queued]>
[2023-10-03T10:16:55.111+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:55.316+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-17 00:00:00+00:00
[2023-10-03T10:16:55.356+0000] {standard_task_runner.py:57} INFO - Started process 3991 to run task
[2023-10-03T10:16:55.373+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-17T00:00:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp6kw04ol3']
[2023-10-03T10:16:55.403+0000] {standard_task_runner.py:85} INFO - Job 425: Subtask preprocess_data
[2023-10-03T10:16:55.845+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-17T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:57.087+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-17T00:00:00+00:00'
[2023-10-03T10:16:57.236+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:57.334+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230917T000000, start_date=20231003T101654, end_date=20231003T101657
[2023-10-03T10:16:57.479+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 425 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3991)
[2023-10-03T10:16:57.598+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:57.683+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
