[2023-10-03T08:04:18.043+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.response_check scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T08:04:18.109+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.response_check scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T08:04:18.109+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T08:04:18.356+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): response_check> on 2023-09-30 00:00:00+00:00
[2023-10-03T08:04:18.407+0000] {standard_task_runner.py:57} INFO - Started process 864 to run task
[2023-10-03T08:04:18.433+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'response_check', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmprjk9nr16']
[2023-10-03T08:04:18.433+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask response_check
[2023-10-03T08:04:18.579+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.response_check scheduled__2023-09-30T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T08:04:18.928+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='response_check' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T08:04:18.929+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: _response_check() missing 1 required positional argument: 'response'
[2023-10-03T08:04:18.952+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=response_check, execution_date=20230930T000000, start_date=20231003T080418, end_date=20231003T080418
[2023-10-03T08:04:19.047+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 25 for task response_check (_response_check() missing 1 required positional argument: 'response'; 864)
[2023-10-03T08:04:19.090+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T08:04:19.144+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
