[2023-10-03T09:53:14.367+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.537+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.543+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:14.740+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T09:53:14.793+0000] {standard_task_runner.py:57} INFO - Started process 3092 to run task
[2023-10-03T09:53:14.839+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp8iqsatcy']
[2023-10-03T09:53:14.844+0000] {standard_task_runner.py:85} INFO - Job 176: Subtask preprocess_data
[2023-10-03T09:53:15.372+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:16.652+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T09:53:16.653+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:16.727+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T095314, end_date=20231003T095316
[2023-10-03T09:53:16.812+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 176 for task preprocess_data (name 'task_instance' is not defined; 3092)
[2023-10-03T09:53:16.914+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:17.294+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:45.791+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:02:45.976+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:02:45.976+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:46.150+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T10:02:46.191+0000] {standard_task_runner.py:57} INFO - Started process 3393 to run task
[2023-10-03T10:02:46.196+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp7qd4abzy']
[2023-10-03T10:02:46.206+0000] {standard_task_runner.py:85} INFO - Job 252: Subtask preprocess_data
[2023-10-03T10:02:46.338+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:46.471+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T10:02:46.474+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:46.500+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T100245, end_date=20231003T100246
[2023-10-03T10:02:46.528+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 252 for task preprocess_data (name 'task_instance' is not defined; 3393)
[2023-10-03T10:02:46.568+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:46.590+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:23.555+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:06:23.627+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:06:23.634+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:23.736+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T10:06:23.752+0000] {standard_task_runner.py:57} INFO - Started process 3636 to run task
[2023-10-03T10:06:23.778+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp9tsxm236']
[2023-10-03T10:06:23.783+0000] {standard_task_runner.py:85} INFO - Job 340: Subtask preprocess_data
[2023-10-03T10:06:23.942+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:24.542+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T10:06:24.579+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:24.620+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T100623, end_date=20231003T100624
[2023-10-03T10:06:24.668+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 340 for task preprocess_data ('NoneType' object has no attribute 'get'; 3636)
[2023-10-03T10:06:24.682+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:24.732+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:56.432+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.565+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.571+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:56.725+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-27 00:00:00+00:00
[2023-10-03T10:16:56.777+0000] {standard_task_runner.py:57} INFO - Started process 3994 to run task
[2023-10-03T10:16:56.807+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpseqcwd4_']
[2023-10-03T10:16:56.808+0000] {standard_task_runner.py:85} INFO - Job 428: Subtask preprocess_data
[2023-10-03T10:16:57.350+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-27T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:58.391+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-10-03T10:16:58.466+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:58.497+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230927T000000, start_date=20231003T101656, end_date=20231003T101658
[2023-10-03T10:16:58.699+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 428 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3994)
[2023-10-03T10:16:58.783+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:58.905+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
