[2023-10-03T09:53:15.188+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T09:53:15.253+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T09:53:15.254+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:15.522+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-20 00:00:00+00:00
[2023-10-03T09:53:15.685+0000] {standard_task_runner.py:57} INFO - Started process 3094 to run task
[2023-10-03T09:53:15.713+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-20T00:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpctd0zr3t']
[2023-10-03T09:53:15.775+0000] {standard_task_runner.py:85} INFO - Job 178: Subtask preprocess_data
[2023-10-03T09:53:16.267+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:17.393+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-20T00:00:00+00:00'
[2023-10-03T09:53:17.400+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:17.433+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230920T000000, start_date=20231003T095315, end_date=20231003T095317
[2023-10-03T09:53:17.572+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 178 for task preprocess_data (name 'task_instance' is not defined; 3094)
[2023-10-03T09:53:17.660+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:17.857+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:44.266+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T10:02:44.412+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T10:02:44.412+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:44.567+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-20 00:00:00+00:00
[2023-10-03T10:02:44.583+0000] {standard_task_runner.py:57} INFO - Started process 3388 to run task
[2023-10-03T10:02:44.602+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-20T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp1mlaav2w']
[2023-10-03T10:02:44.614+0000] {standard_task_runner.py:85} INFO - Job 247: Subtask preprocess_data
[2023-10-03T10:02:44.919+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:45.458+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-20T00:00:00+00:00'
[2023-10-03T10:02:45.459+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:45.490+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230920T000000, start_date=20231003T100244, end_date=20231003T100245
[2023-10-03T10:02:45.577+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 247 for task preprocess_data (name 'task_instance' is not defined; 3388)
[2023-10-03T10:02:45.627+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:45.691+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:21.010+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T10:06:21.084+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T10:06:21.086+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:21.231+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-20 00:00:00+00:00
[2023-10-03T10:06:21.276+0000] {standard_task_runner.py:57} INFO - Started process 3632 to run task
[2023-10-03T10:06:21.290+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-20T00:00:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpuchtr7ja']
[2023-10-03T10:06:21.300+0000] {standard_task_runner.py:85} INFO - Job 337: Subtask preprocess_data
[2023-10-03T10:06:21.573+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:22.490+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-20T00:00:00+00:00'
[2023-10-03T10:06:22.582+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:22.634+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230920T000000, start_date=20231003T100621, end_date=20231003T100622
[2023-10-03T10:06:22.707+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 337 for task preprocess_data ('NoneType' object has no attribute 'get'; 3632)
[2023-10-03T10:06:22.748+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:22.859+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:56.310+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.443+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.445+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:56.631+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-20 00:00:00+00:00
[2023-10-03T10:16:56.646+0000] {standard_task_runner.py:57} INFO - Started process 3992 to run task
[2023-10-03T10:16:56.676+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-20T00:00:00+00:00', '--job-id', '427', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpba29w9bd']
[2023-10-03T10:16:56.677+0000] {standard_task_runner.py:85} INFO - Job 427: Subtask preprocess_data
[2023-10-03T10:16:57.309+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-20T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:58.385+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-20T00:00:00+00:00'
[2023-10-03T10:16:58.475+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:58.567+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230920T000000, start_date=20231003T101656, end_date=20231003T101658
[2023-10-03T10:16:58.809+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 427 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3992)
[2023-10-03T10:16:58.922+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:59.032+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
