[2023-10-03T09:53:25.300+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T09:53:25.309+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T09:53:25.309+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:25.329+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T09:53:25.335+0000] {standard_task_runner.py:57} INFO - Started process 3115 to run task
[2023-10-03T09:53:25.337+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpfaqa11ix']
[2023-10-03T09:53:25.337+0000] {standard_task_runner.py:85} INFO - Job 192: Subtask preprocess_data
[2023-10-03T09:53:25.384+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:25.504+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T09:53:25.507+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:25.516+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T095325, end_date=20231003T095325
[2023-10-03T09:53:25.534+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 192 for task preprocess_data (name 'task_instance' is not defined; 3115)
[2023-10-03T09:53:25.549+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:25.564+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:55.127+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:02:55.143+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:02:55.143+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:55.174+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T10:02:55.180+0000] {standard_task_runner.py:57} INFO - Started process 3413 to run task
[2023-10-03T10:02:55.193+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp0ra9wihm']
[2023-10-03T10:02:55.199+0000] {standard_task_runner.py:85} INFO - Job 261: Subtask preprocess_data
[2023-10-03T10:02:55.274+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:55.626+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T10:02:55.633+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:55.685+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T100255, end_date=20231003T100255
[2023-10-03T10:02:55.716+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 261 for task preprocess_data (name 'task_instance' is not defined; 3413)
[2023-10-03T10:02:55.728+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:55.764+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:30.399+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:06:30.412+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:06:30.412+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:30.439+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T10:06:30.455+0000] {standard_task_runner.py:57} INFO - Started process 3650 to run task
[2023-10-03T10:06:30.460+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpls5b548h']
[2023-10-03T10:06:30.461+0000] {standard_task_runner.py:85} INFO - Job 349: Subtask preprocess_data
[2023-10-03T10:06:30.559+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:30.851+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T10:06:30.867+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:30.893+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T100630, end_date=20231003T100630
[2023-10-03T10:06:30.920+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 349 for task preprocess_data ('NoneType' object has no attribute 'get'; 3650)
[2023-10-03T10:06:30.931+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:30.955+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:17:06.002+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:17:06.053+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2023-10-03T10:17:06.054+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:17:06.127+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-30 00:00:00+00:00
[2023-10-03T10:17:06.134+0000] {standard_task_runner.py:57} INFO - Started process 4028 to run task
[2023-10-03T10:17:06.149+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '444', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpraiu9owg']
[2023-10-03T10:17:06.150+0000] {standard_task_runner.py:85} INFO - Job 444: Subtask preprocess_data
[2023-10-03T10:17:06.227+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-30T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:17:06.400+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2023-10-03T10:17:06.425+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:17:06.442+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230930T000000, start_date=20231003T101706, end_date=20231003T101706
[2023-10-03T10:17:06.474+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 444 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 4028)
[2023-10-03T10:17:06.520+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:17:06.613+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
