[2023-10-03T09:53:16.011+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T09:53:16.115+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T09:53:16.117+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:16.492+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T09:53:16.524+0000] {standard_task_runner.py:57} INFO - Started process 3098 to run task
[2023-10-03T09:53:16.584+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpt6i950ch']
[2023-10-03T09:53:16.601+0000] {standard_task_runner.py:85} INFO - Job 181: Subtask preprocess_data
[2023-10-03T09:53:17.199+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:18.468+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T09:53:18.469+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:18.565+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T095316, end_date=20231003T095318
[2023-10-03T09:53:18.701+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 181 for task preprocess_data (name 'task_instance' is not defined; 3098)
[2023-10-03T09:53:18.803+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:18.910+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:44.668+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:02:44.776+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:02:44.776+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:44.953+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T10:02:44.982+0000] {standard_task_runner.py:57} INFO - Started process 3390 to run task
[2023-10-03T10:02:45.020+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmprxn_wo87']
[2023-10-03T10:02:45.021+0000] {standard_task_runner.py:85} INFO - Job 249: Subtask preprocess_data
[2023-10-03T10:02:45.300+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:45.744+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T10:02:45.799+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:45.867+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T100244, end_date=20231003T100245
[2023-10-03T10:02:46.044+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 249 for task preprocess_data (name 'task_instance' is not defined; 3390)
[2023-10-03T10:02:46.120+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:46.242+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:21.524+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:06:21.703+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:06:21.710+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:21.914+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T10:06:21.988+0000] {standard_task_runner.py:57} INFO - Started process 3634 to run task
[2023-10-03T10:06:22.004+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp6qxtghw1']
[2023-10-03T10:06:22.027+0000] {standard_task_runner.py:85} INFO - Job 338: Subtask preprocess_data
[2023-10-03T10:06:22.274+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:23.182+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T10:06:23.246+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:23.283+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T100621, end_date=20231003T100623
[2023-10-03T10:06:23.400+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 338 for task preprocess_data ('NoneType' object has no attribute 'get'; 3634)
[2023-10-03T10:06:23.438+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:23.527+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:56.384+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.519+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [queued]>
[2023-10-03T10:16:56.536+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:56.752+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-25 00:00:00+00:00
[2023-10-03T10:16:56.959+0000] {standard_task_runner.py:57} INFO - Started process 3996 to run task
[2023-10-03T10:16:56.981+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-25T00:00:00+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp04bv8k_i']
[2023-10-03T10:16:57.002+0000] {standard_task_runner.py:85} INFO - Job 429: Subtask preprocess_data
[2023-10-03T10:16:57.402+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-25T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:58.526+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-25T00:00:00+00:00'
[2023-10-03T10:16:58.608+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:58.715+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230925T000000, start_date=20231003T101656, end_date=20231003T101658
[2023-10-03T10:16:58.937+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 429 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3996)
[2023-10-03T10:16:59.025+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:59.083+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
