[2023-10-02T12:47:15.383+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exercise3.print_task_dag scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-02T12:47:15.411+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exercise3.print_task_dag scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-10-02T12:47:15.412+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-02T12:47:15.444+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): print_task_dag> on 2023-10-01 00:00:00+00:00
[2023-10-02T12:47:15.449+0000] {standard_task_runner.py:57} INFO - Started process 1053 to run task
[2023-10-02T12:47:15.457+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'exercise3', 'print_task_dag', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/exercise3.py', '--cfg-path', '/tmp/tmp87g55_3k']
[2023-10-02T12:47:15.457+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask print_task_dag
[2023-10-02T12:47:15.666+0000] {task_command.py:410} INFO - Running <TaskInstance: exercise3.print_task_dag scheduled__2023-10-01T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-02T12:47:15.870+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exercise3' AIRFLOW_CTX_TASK_ID='print_task_dag' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-10-02T12:47:15.871+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-10-02T12:47:15.871+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo '<Task(BashOperator): print_task_dag> is running in the <DAG: exercise3> pipeline"]
[2023-10-02T12:47:15.915+0000] {subprocess.py:86} INFO - Output:
[2023-10-02T12:47:15.917+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-10-02T12:47:15.918+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-10-02T12:47:15.918+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-02T12:47:15.935+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-02T12:47:15.941+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=exercise3, task_id=print_task_dag, execution_date=20231001T000000, start_date=20231002T124715, end_date=20231002T124715
[2023-10-02T12:47:15.978+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task print_task_dag (Bash command failed. The command returned a non-zero exit code 2.; 1053)
[2023-10-02T12:47:16.002+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-02T12:47:16.031+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
