[2023-10-03T09:53:15.976+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T09:53:16.180+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T09:53:16.193+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:16.321+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-15 00:00:00+00:00
[2023-10-03T09:53:16.328+0000] {standard_task_runner.py:57} INFO - Started process 3095 to run task
[2023-10-03T09:53:16.352+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-15T00:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpbr8294ij']
[2023-10-03T09:53:16.363+0000] {standard_task_runner.py:85} INFO - Job 180: Subtask preprocess_data
[2023-10-03T09:53:16.965+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:18.149+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-15T00:00:00+00:00'
[2023-10-03T09:53:18.149+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:18.243+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230915T000000, start_date=20231003T095315, end_date=20231003T095318
[2023-10-03T09:53:18.373+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 180 for task preprocess_data (name 'task_instance' is not defined; 3095)
[2023-10-03T09:53:18.439+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:18.563+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:42.741+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T10:02:42.803+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T10:02:42.803+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:43.059+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-15 00:00:00+00:00
[2023-10-03T10:02:43.105+0000] {standard_task_runner.py:57} INFO - Started process 3386 to run task
[2023-10-03T10:02:43.124+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-15T00:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp8oex1uac']
[2023-10-03T10:02:43.142+0000] {standard_task_runner.py:85} INFO - Job 245: Subtask preprocess_data
[2023-10-03T10:02:43.291+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:44.329+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-15T00:00:00+00:00'
[2023-10-03T10:02:44.330+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:44.383+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230915T000000, start_date=20231003T100242, end_date=20231003T100244
[2023-10-03T10:02:44.527+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 245 for task preprocess_data (name 'task_instance' is not defined; 3386)
[2023-10-03T10:02:44.573+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:44.670+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:20.208+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T10:06:20.293+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T10:06:20.309+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:20.771+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-15 00:00:00+00:00
[2023-10-03T10:06:20.875+0000] {standard_task_runner.py:57} INFO - Started process 3631 to run task
[2023-10-03T10:06:20.921+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-15T00:00:00+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpntwr6w7a']
[2023-10-03T10:06:20.954+0000] {standard_task_runner.py:85} INFO - Job 336: Subtask preprocess_data
[2023-10-03T10:06:21.273+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:21.996+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-15T00:00:00+00:00'
[2023-10-03T10:06:22.037+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:22.064+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230915T000000, start_date=20231003T100620, end_date=20231003T100622
[2023-10-03T10:06:22.179+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 336 for task preprocess_data ('NoneType' object has no attribute 'get'; 3631)
[2023-10-03T10:06:22.343+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:22.464+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:49.641+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T10:16:50.081+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [queued]>
[2023-10-03T10:16:50.089+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:50.472+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-15 00:00:00+00:00
[2023-10-03T10:16:50.633+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-15T00:00:00+00:00', '--job-id', '423', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpui_pew8o']
[2023-10-03T10:16:50.634+0000] {standard_task_runner.py:85} INFO - Job 423: Subtask preprocess_data
[2023-10-03T10:16:50.670+0000] {standard_task_runner.py:57} INFO - Started process 3984 to run task
[2023-10-03T10:16:51.212+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-15T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:53.143+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-15T00:00:00+00:00'
[2023-10-03T10:16:53.286+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:53.399+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230915T000000, start_date=20231003T101649, end_date=20231003T101653
[2023-10-03T10:16:53.682+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 423 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3984)
[2023-10-03T10:16:53.873+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:54.105+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
