[2023-10-03T09:53:14.611+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.792+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T09:53:14.802+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T09:53:14.968+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-24 00:00:00+00:00
[2023-10-03T09:53:15.003+0000] {standard_task_runner.py:57} INFO - Started process 3093 to run task
[2023-10-03T09:53:15.026+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-24T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp_0nq3yp7']
[2023-10-03T09:53:15.074+0000] {standard_task_runner.py:85} INFO - Job 177: Subtask preprocess_data
[2023-10-03T09:53:15.679+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T09:53:16.381+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-24T00:00:00+00:00'
[2023-10-03T09:53:16.381+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 53, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T09:53:16.471+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230924T000000, start_date=20231003T095314, end_date=20231003T095316
[2023-10-03T09:53:16.704+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 177 for task preprocess_data (name 'task_instance' is not defined; 3093)
[2023-10-03T09:53:16.823+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T09:53:17.027+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:02:44.620+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T10:02:44.794+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T10:02:44.794+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:02:44.881+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-24 00:00:00+00:00
[2023-10-03T10:02:44.942+0000] {standard_task_runner.py:57} INFO - Started process 3389 to run task
[2023-10-03T10:02:44.977+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-24T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpt2anjd2k']
[2023-10-03T10:02:44.993+0000] {standard_task_runner.py:85} INFO - Job 248: Subtask preprocess_data
[2023-10-03T10:02:45.292+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:02:45.864+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-24T00:00:00+00:00'
[2023-10-03T10:02:45.867+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 63, in _preprocess_data
    result_by_key = task_instance.xcom_pull(task_ids="task_get_op", key="return_value")
NameError: name 'task_instance' is not defined
[2023-10-03T10:02:45.955+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230924T000000, start_date=20231003T100244, end_date=20231003T100245
[2023-10-03T10:02:46.020+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 248 for task preprocess_data (name 'task_instance' is not defined; 3389)
[2023-10-03T10:02:46.120+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:02:46.223+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:06:23.651+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T10:06:23.710+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T10:06:23.715+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:06:23.807+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-24 00:00:00+00:00
[2023-10-03T10:06:23.838+0000] {standard_task_runner.py:57} INFO - Started process 3637 to run task
[2023-10-03T10:06:23.853+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-24T00:00:00+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmpo_2lmylw']
[2023-10-03T10:06:23.861+0000] {standard_task_runner.py:85} INFO - Job 341: Subtask preprocess_data
[2023-10-03T10:06:23.970+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:06:24.449+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-24T00:00:00+00:00'
[2023-10-03T10:06:24.494+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 65, in _preprocess_data
    result_filtered = _extract_relevant_data(result_dict)
  File "/opt/airflow/dags/rocket_launch.py", line 56, in _extract_relevant_data
    "status": x.get("status").get("abbrev"),
AttributeError: 'NoneType' object has no attribute 'get'
[2023-10-03T10:06:24.529+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230924T000000, start_date=20231003T100623, end_date=20231003T100624
[2023-10-03T10:06:24.599+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 341 for task preprocess_data ('NoneType' object has no attribute 'get'; 3637)
[2023-10-03T10:06:24.643+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:06:24.714+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-03T10:16:57.992+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T10:16:58.122+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [queued]>
[2023-10-03T10:16:58.123+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-10-03T10:16:58.336+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): preprocess_data> on 2023-09-24 00:00:00+00:00
[2023-10-03T10:16:58.397+0000] {standard_task_runner.py:57} INFO - Started process 3999 to run task
[2023-10-03T10:16:58.412+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rocket_launch2', 'preprocess_data', 'scheduled__2023-09-24T00:00:00+00:00', '--job-id', '434', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmp405btkbq']
[2023-10-03T10:16:58.418+0000] {standard_task_runner.py:85} INFO - Job 434: Subtask preprocess_data
[2023-10-03T10:16:58.874+0000] {task_command.py:410} INFO - Running <TaskInstance: rocket_launch2.preprocess_data scheduled__2023-09-24T00:00:00+00:00 [running]> on host e870058fa168
[2023-10-03T10:16:59.385+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rocket_launch2' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2023-09-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-24T00:00:00+00:00'
[2023-10-03T10:16:59.426+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 64, in _preprocess_data
    response_dict = json.loads(response)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[2023-10-03T10:16:59.450+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=rocket_launch2, task_id=preprocess_data, execution_date=20230924T000000, start_date=20231003T101658, end_date=20231003T101659
[2023-10-03T10:16:59.514+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 434 for task preprocess_data (the JSON object must be str, bytes or bytearray, not NoneType; 3999)
[2023-10-03T10:16:59.600+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-03T10:16:59.692+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
